### PR TITLE
chore(ci): remove obsolete steps from release

### LINKED ISSUE #70: GitHub release does not work
The script to release to GitHub has been copied and pasted form a single Maven project template and does not work for this project.

### PR DESCRIPTION
**Pull request by pihme**
closes #70 

# Changes
* In general this PR reduces the steps that are done during a release, and adds documentation to explain what to expect
* Removes the upload steps from the release script (the JAR artifacts are published to Maven Central anyway; the other artifacts would require much more work, and it's not clear whether it would be worth it)

### CODE REVIEW

**Review by Zelldon — APPROVED** [review]
We have a release :thinking: didn't we just deploy new versions?

**Comment by pihme** [comment]
> We have a release 🤔 didn't we just deploy new versions?

We deploy new versions for production. 

We have a release so that the Java artifacts are available in Maven central. (Bernd once wanted to use the API to interact with Camunda cloud)

**Comment by Zelldon** [comment]
Might make sense to separate this then in a new repo ?

**Pull request merged**
