### PR TITLE
Deploy multi version worker

### PR DESCRIPTION
**Pull request by Zelldon**
I wanted to replace the [deploy different version](https://github.com/zeebe-io/zeebe-chaos/blob/master/chaos-experiments/scripts/deploy-different-versions.sh) scripts with a kotlin worker, in general it worked and I like the resultat but I had problem to run it.

I get always:

```
18:31:57.681 [grpc-default-executor-4] ERROR Java Client: io.zeebe.client.impl.oauth.OAuthCredentialsProvider - Failed while fetching credentials: 
java.io.IOException: Failed while requesting access token with status code 429 and message Too Many Requests.
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.fetchCredentials(OAuthCredentialsProvider.java:184) ~[chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.refreshCredentials(OAuthCredentialsProvider.java:133) ~[chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.shouldRetryRequest(OAuthCredentialsProvider.java:101) ~[chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.zeebe.client.impl.RetriableClientFutureImpl.onError(RetriableClientFutureImpl.java:48) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
18:31:59.998 [grpc-default-executor-4] ERROR Java Client: io.zeebe.client.impl.oauth.OAuthCredentialsProvider - Failed while fetching credentials: 
java.io.IOException: Failed while requesting access token with status code 429 and message Too Many Requests.
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.fetchCredentials(OAuthCredentialsProvider.java:184) ~[chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.refreshCredentials(OAuthCredentialsProvider.java:133) ~[chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.shouldRetryRequest(OAuthCredentialsProvider.java:101) ~[chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.zeebe.client.impl.RetriableClientFutureImpl.onError(RetriableClientFutureImpl.java:48) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
18:32:00.445 [grpc-default-executor-4] ERROR Java Client: io.zeebe.client.impl.oauth.OAuthCredentialsProvider - Failed while fetching credentials: 
java.io.IOException: Failed while requesting access token with status code 429 and message Too Many Requests.
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.fetchCredentials(OAuthCredentialsProvider.java:184) ~[chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.refreshCredentials(OAuthCredentialsProvider.java:133) ~[chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.shouldRetryRequest(OAuthCredentialsProvider.java:101) ~[chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.zeebe.client.impl.RetriableClientFutureImpl.onError(RetriableClientFutureImpl.java:48) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [chaosWorker.jar:2.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

It seems to be a problem with creating multiple clients in one application?

Maybe @pihme @saig0 has an idea?

### CODE REVIEW

**Comment by pihme** [comment]
@Zelldon About multiple clients in one application. That does ring a bell for me.

I remember that the default credentials cache was not fit for the cloud + multiple clusters. It only sets the audience, but this is the same for all cloud clients. (io.zeebe.client.impl.ZeebeClientBuilderImpl#createDefaultCredentialsProvider)

I think the solution was to set more fields. (io.zeebe.clustertestbench.bootstrap.Launcher#buildCredentialsProvider)

**Comment by pihme** [comment]
@Zelldon After looking deeper into it, I have no explanation.

**Comment by Zelldon** [comment]
Thanks @pihme for looking into ir

**Comment by Zelldon** [comment]
Hey @pihme thanks for the pointer!

I checked the testbench code again and realized that we using there different environment variables, see here https://github.com/zeebe-io/zeebe-cluster-testbench/blob/develop/core/src/main/java/io/zeebe/clustertestbench/bootstrap/BootstrapFromEnvVars.java#L29-L30 The issue is if you create a client and have the zeebe env set, as I have in the chaos worker, then they are used in the builder of the ZeebeClient and overwriting value even if they already set. https://github.com/camunda-cloud/zeebe/blob/develop/clients/java/src/main/java/io/zeebe/client/impl/oauth/OAuthCredentialsProviderBuilder.java#L154-L160
This is totally unexpected tbh :roll_eyes:

**Comment by Zelldon** [comment]
Hey @pihme I found the issue. As written above the problem was the environment variables :man_facepalming:. I fixed that and we now have our first migrated script, which is replaced by a kotlin worker :tada: 

Example output:

```
18:06:02.595 [pool-3-thread-4] INFO  Java Client: io.zeebe.chaos.DeployMultipleVersionsHandler - Handle job deploy-different-versions.sh
18:06:02.620 [pool-3-thread-4] INFO  Java Client: io.zeebe.chaos.DeployMultipleVersionsHandler - Connected to 1f1f54c1-526f-4a71-adee-54bc84e5dfae.zeebe.ultrawombat.com:443, start deploying multiple versions...
18:06:04.981 [pool-3-thread-4] INFO  Java Client: io.zeebe.chaos.DeployMultipleVersionsHandler - Deployed 10 different versions of process multiVersion, last version: 74. Complete deploy-different-versions.sh
```

**Review by pihme — APPROVED** [review]
:tada:

**Comment by pihme** [comment]
@Zelldon:  Seems you have more fun with Kotlin than with Shell Scripts :-)

**Comment by pihme** [comment]
> Hey @pihme I found the issue. As written above the problem was the environment variables man_facepalming. I fixed that and we now have our first migrated script, which is replaced by a kotlin worker tada
> 
> Example output:
> 
> ```
> 18:06:02.595 [pool-3-thread-4] INFO  Java Client: io.zeebe.chaos.DeployMultipleVersionsHandler - Handle job deploy-different-versions.sh
> 18:06:02.620 [pool-3-thread-4] INFO  Java Client: io.zeebe.chaos.DeployMultipleVersionsHandler - Connected to 1f1f54c1-526f-4a71-adee-54bc84e5dfae.zeebe.ultrawombat.com:443, start deploying multiple versions...
> 18:06:04.981 [pool-3-thread-4] INFO  Java Client: io.zeebe.chaos.DeployMultipleVersionsHandler - Deployed 10 different versions of process multiVersion, last version: 74. Complete deploy-different-versions.sh
> ```

Still wondering how we arrive at version 74 if we deploy the workflow 10 times.

**Comment by Zelldon** [comment]
Both is fun but this has less pain😀 yes the numbers are because I had a test cluster where I tested the implementation 😊

**Comment by Zelldon** [comment]
Bors r+

**Pull request merged**
