### PR TITLE
[Backport 0.26]  Add more details to failure msgs

### PR DESCRIPTION
**Pull request by Zelldon**
Backports https://github.com/zeebe-io/zeebe-cluster-testbench/pull/353

### CODE REVIEW

**Comment by korthout** [comment]
@Zelldon FYI: The backport bot is also enabled in this project

**Comment by Zelldon** [comment]
Was not sure how well it works😅 I also searched for labels and havent found them

**Comment by korthout** [comment]
@Zelldon Ah yes, it was added only recently and was not yet used apparently. A `backport stable/0.26` label is available for future backportings :)

**Review by pihme — APPROVED** [review]

**Pull request merged**
