### PR TITLE
fix(processes): rename used region for QA runs

### PR DESCRIPTION
**Pull request by korthout**
The region name has changed:
- from `Belgium, Europe (europe-west1) aka. new chaos`
- to `Belgium, Europe (europe-west1)`

### CODE REVIEW

**Review by remcowesterhoud — APPROVED** [review]
Thanks @korthout 

💭 We should probably move to region UUID instead of names 😄

**Comment by korthout** [comment]
Seems bors is broken since:
- #583 

I'll open a pull request to fix it

**Comment by korthout** [comment]
bors merge

**Pull request merged**
