### PR TITLE
Forward chaos worker to 1.x

### PR DESCRIPTION
**Pull request by Zelldon**
I tried to forward all changes I recently did on stable/0.26 to 1.x. 

This includes:

 * https://github.com/zeebe-io/zeebe-cluster-testbench/pull/269
 * https://github.com/zeebe-io/zeebe-cluster-testbench/pull/273
 * https://github.com/zeebe-io/zeebe-cluster-testbench/pull/284
 * https://github.com/zeebe-io/zeebe-cluster-testbench/pull/287
 * https://github.com/zeebe-io/zeebe-cluster-testbench/pull/288

### CODE REVIEW

**Review by pihme — APPROVED** [review]
In my mind the code changes here are fine.

The one area of caution is in the chaos repository. I am not sure that all scripts we use work equally well with 0.26 and 1.0.

**Comment by Zelldon** [comment]
@pihme fyi i created a separate release on the Zeebe chaos repo https://github.com/zeebe-io/zeebe-chaos/releases/tag/0.26.1, which is used by the stable/0.26 Testbench https://github.com/zeebe-io/zeebe-cluster-testbench/pull/295 and @korthout migrated the scripts to 1.x https://github.com/zeebe-io/zeebe-chaos/pull/54 which are then used by the 1.x testbench :)

**Comment by pihme** [comment]
@Zelldon Multi version chaos! So exciting :-)

**Pull request merged**
